# Generated by Django 4.2.3 on 2023-07-14 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVATED", "Activated"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("procurement_date", models.DateField(default=datetime.date.today)),
                ("expiry_date", models.DateField()),
                ("token", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_keys",
                        to="school.school",
                    ),
                ),
            ],
        ),
    ]
