# Generated by Django 4.2.3 on 2023-07-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("key_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesskey",
            name="key_duration",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("YEARLY", "Yearly"),
                ],
                default="MONTHLY",
                max_length=10,
            ),
        ),
    ]
