# Generated by Django 4.2.3 on 2023-07-17 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="num_of_users",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.CreateModel(
            name="SchoolITPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="it_personnel",
                        to="school.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="it_personnel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
