# Generated by Django 4.2.3 on 2023-07-17 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_school_num_of_users_schoolitpersonnel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="type",
            new_name="school_type",
        ),
        migrations.RemoveField(
            model_name="school",
            name="payment_plan",
        ),
    ]
