# Generated by Django 4.2.3 on 2023-07-19 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_rename_type_school_school_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolITPersonnel",
        ),
    ]
